services:
  - type: web
    name: django-joblib-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ml_project.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ml_project.settings
      - key: SECRET_KEY
        generateValue: true
